# Generated by Django 5.2.6 on 2025-10-09 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='CHANGEME', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('leaders', models.ManyToManyField(related_name='team_leaders', to='todo.user')),
                ('members', models.ManyToManyField(related_name='team_members', to='todo.user')),
            ],
        ),
        migrations.AddField(
            model_name='todoitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.team'),
        ),
    ]
