# Generated by Django 5.2.6 on 2025-10-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todoitem_assigned_user_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friend_perms',
            field=models.CharField(choices=[('P', 'None'), ('V', 'View'), ('M', 'Modify')], default='V', max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='friend_requests',
            field=models.ManyToManyField(to='todo.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(to='todo.user'),
        ),
    ]
