# Generated by Django 5.2.6 on 2025-10-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_user_friend_perms_user_friend_requests_user_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(default='display_name', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
