# Generated by Django 5.2.6 on 2025-10-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_remove_user_password_user_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='everyone_perms',
            field=models.CharField(choices=[('P', 'None'), ('V', 'View'), ('M', 'Modify')], default='P', max_length=1),
        ),
    ]
