# Generated by Django 5.2.6 on 2025-11-07 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_user_everyone_perms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Todo_User',
        ),
    ]
